
services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    image: interfaz-web-desarrollo:latest
    volumes:
      - .:/code
    environment:
      - FLASK_ENV=development
